FROM debian:bookworm-slim AS builder

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=America/Sao_Paulo

SHELL ["/bin/bash", "-c"]

ARG SDL_VERSION
ARG SDL_TTF_VERSION
ARG SDL_IMAGE_VERSION
ARG SDL_MIXER_VERSION
ARG SDL_NET_VERSION

ADD fn-native.sh /fn.sh

RUN source /fn.sh && \
    install_build_dependencies && \
    case "$SDL_VERSION" in \
        1.*) \
            install_sdl1 ;; \
        2.*) \
            install_sdl2 SDL2 ${SDL_VERSION} && \
            install_sdl2 SDL2_ttf ${SDL_TTF_VERSION} && \
            install_sdl2 SDL2_image ${SDL_IMAGE_VERSION} && \
            install_sdl2 SDL2_mixer ${SDL_MIXER_VERSION} && \
            install_sdl2 SDL2_net ${SDL_NET_VERSION} ;; \
        3.*) \
            install_sdl3_dependencies && \
            install_sdl3 SDL3 ${SDL_VERSION} && \
            install_sdl3 SDL3_ttf ${SDL_TTF_VERSION} && \
            install_sdl3 SDL3_image ${SDL_IMAGE_VERSION} && \
            install_sdl3 SDL3_mixer ${SDL_MIXER_VERSION} && \
            install_sdl3 SDL3_net ${SDL_NET_VERSION} ;; \
    esac && \
    slim_installed_sdl && \
    cleanup_image

FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=America/Sao_Paulo

SHELL ["/bin/bash", "-c"]

ARG SDL_VERSION

ADD fn-native.sh /fn.sh

RUN source /fn.sh && install_runtime_dependencies && cleanup_image

COPY --from=builder /usr/local /usr/local

RUN source /fn.sh && slim_installed_sdl

EXPOSE 8080
