name: ci-docker

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: 'SDL version target (sdl1, sdl2, sdl3)'
        required: true
        default: 'sdl2'

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load environment variables from selected file
        run: |
          echo "Using version: ${{ github.event.inputs.target_version }}"
          ENV_FILE=".github/env/${{ github.event.inputs.target_version }}.env"
          if [ ! -f "$ENV_FILE" ]; then
            echo "Env file not found: $ENV_FILE"
            exit 1
          fi
          set -a
          source "$ENV_FILE"
          set +a
          echo "SDL_VERSION=$SDL_VERSION" >> $GITHUB_ENV
          echo "SDL_TTF_VERSION=$SDL_TTF_VERSION" >> $GITHUB_ENV
          echo "SDL_IMAGE_VERSION=$SDL_IMAGE_VERSION" >> $GITHUB_ENV
          echo "SDL_MIXER_VERSION=$SDL_MIXER_VERSION" >> $GITHUB_ENV
          echo "SDL_NET_VERSION=$SDL_NET_VERSION" >> $GITHUB_ENV
          echo "EMSDK_VERSION=$EMSDK_VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "DOCKERHUB_REPONAME=sdl-compiler" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            SDL_VERSION=${{ env.SDL_VERSION }}
            SDL_TTF_VERSION=${{ env.SDL_TTF_VERSION }}
            SDL_IMAGE_VERSION=${{ env.SDL_IMAGE_VERSION }}
            SDL_MIXER_VERSION=${{ env.SDL_MIXER_VERSION }}
            SDL_NET_VERSION=${{ env.SDL_NET_VERSION }}
            EMSDK_VERSION=${{ env.EMSDK_VERSION }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}:${{ env.TAG_NAME }}
