name: ci-docker

on:
 workflow_dispatch:
    inputs:
        sdlversion:
          default: "2.32.4"
          description: "SDL Version"
        sdlttfversion:
            default: "2.22.0"
            description: "SDLTTF Version"
        sdlimageversion:
            default: "2.8.2"
            description: "SDLImage Version"
        sdlmixerversion:
            default: "2.8.0"
            description: "SDLMixer Version"
        sdlnetversion:
            default: "2.2.0"
            description: "SDLNet Version"
            
jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    environment: DockerHub
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          # - linux/arm/v7
          # - linux/arm64/v8
          # - linux/386
          # - linux/ppc64le
          # - linux/s390x

    env:
      DOCKERHUB_REPONAME: sdl-compiler
      DOCKERHUB_REPOTAG: ${{ github.event.inputs.sdlnetversion }}

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          path: .
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}
          provider: dockerhub
          short_description: 'A Docker Image for SDL Development'
          readme_file: 'README.md'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            SDL_VERSION=${{ github.event.inputs.sdlversion }}
            SDL_TTF_VERSION=${{ github.event.inputs.sdlttfversion }}
            SDL_IMAGE_VERSION=${{ github.event.inputs.sdlimageversion }}
            SDL_MIXER_VERSION=${{ github.event.inputs.sdlmixerversion }}
            SDL_NET_VERSION=${{ github.event.inputs.sdlnetversion }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPONAME }}:${{ env.DOCKERHUB_REPOTAG }}

